const data = {
  products: [
    {
      name: 'Maths',
      Scheme: '2019',
      slug: 'Maths-S1',
      image: '/images/p1.jpg',
      price: 150,
      seller: 'Team-Recirculate',
      rating: 4.5,
      countInStock: 15,
      disciption: 'This is S1 text book',
    },
    {
      name: 'Graphic',
      Scheme: '2019',
      slug: 'Graphics-S1',
      category: 'Common',
      image: '/images/p2.jpg',
      price: 170,
      seller: 'Team-Recirculate',
      rating: 4.5,
      countInStock: 15,
      disciption: 'This is S1 text book',
    },
    {
      name: 'Maths',
      Scheme: '2019',
      slug: 'Maths-S2',
      image: '/images/p1.jpg',
      price: 150,
      seller: 'Team-Recirculate',
      rating: 4.5,
      countInStock: 15,
      disciption: 'This is S1 text book',
    },
    {
      name: 'Graphic',
      Scheme: '2019',
      slug: 'Graphics-S2',
      category: 'Common',
      image: '/images/p2.jpg',
      price: 170,
      seller: 'Team-Recirculate',
      rating: 4.5,
      countInStock: 15,
      disciption: 'This is S1 text book',
    },
  ],
};
export default data;
