import bcrypt from 'bcryptjs';
const sampleData = {
  users: [
    {
      name: 'Rejin C Reji',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Elon Musk',
      email: 'user@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Maths',
      scheme: '2008',
      slug: 'Maths-S1',
      category: 'BTECH-KTU',
      image: '/images/p1.jpg',
      price: 150,
      seller: 'Team-Recirculate',
      rating: 4.7,
      numReviews: 120,
      countInStock: 4,
      description: 'This is S1 text book ',
    },
    {
      // _id: '2',
      name: 'Graphic',
      scheme: '2019',
      slug: 'Graphics-S1',
      category: 'BTECH-KTU',
      image: '/images/p2.jpg',
      price: 170,
      seller: 'Team-Recirculate',
      rating: 4,
      numReviews: 12,
      countInStock: 15,
      description: 'This is S1 text book',
    },
    {
      // _id: '3',
      name: 'Maths S2',
      scheme: '2019',
      slug: 'Maths-S2',
      category: 'BTECH-KTU',
      image: '/images/p3.jpg',
      price: 140,
      seller: 'Team-Recirculate  ',
      rating: 4.5,
      numReviews: 10,
      countInStock: 0,
      description: 'This is S1 text book  ',
    },
    {
      // _id: '4',
      name: 'Graphic S2',
      scheme: '2019',
      slug: 'Graphics-S2',
      category: 'BTECH-KTU',
      image: '/images/p4.jpg',
      price: 180,
      seller: 'Team-Recirculate',
      rating: 4.59,
      numReviews: 16,
      countInStock: 14,
      description: 'This is S1 text book   ',
    },
  ],
};
export default sampleData;
